#!/usr/bin/env python
print "things our interperter knows about at startup:", dir()

nums = [3, 7, 8, 9, 6, 2]

def average(vals):
    total = sum(vals)
    return float(total)/len(vals)

print "the average of nums is", average(nums)

print "things our interperter knows about at the end:", dir()
